services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: flpaydb # Nome do banco 
      POSTGRES_USER: frevolink # Usuário 
      POSTGRES_PASSWORD: flpassword # Senha 
    ports:
      - "5432:5432" # Porta do host:porta do container   
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume para persistência 
volumes:
  postgres_data: # Define o volume nomeado
